version: '3'

networks:
  reverse-public:
    external: true
  reqbot:
    name: reqbot

services:
  backend:
    image: $CI_REGISTRY/$CI_PROJECT_PATH/app:$CI_COMMIT_SHORT_SHA
    build:
      context: .
    restart: always
    environment:
      APP_NAME: website_backend
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DB: website_backend
      REDIS_URL: redis://redis:6379/0
      AUTH_JWT_SECRET: $AUTH_JWT_SECRET
      AUTH_JWT_ALG: HS256
      ACCESS_TOKEN_EXPIRES_SECONDS: $ACCESS_TOKEN_EXPIRES_SECONDS
      LOGIN_TOKEN_TTL_SECONDS: $LOGIN_TOKEN_TTL_SECONDS
      TELEGRAM_BOT_USERNAME: $TELEGRAM_BOT_USERNAME
      TELEGRAM_BOT_SECRET: $TELEGRAM_BOT_SECRET

    networks:
      - reverse-public
      - reqbot
    labels:
      - traefik.enable=true
      - traefik.http.routers.reqbot-api-http.rule=Host(`api.reqbot.iqdev.team`)
      - traefik.http.routers.reqbot-api-http.service=reqbot-api
      - traefik.http.routers.reqbot-api-http.middlewares=ssl-only
      - traefik.http.routers.reqbot-api.rule=Host(`api.reqbot.iqdev.team`)
      - traefik.http.routers.reqbot-api.service=reqbot-api
      - traefik.http.routers.reqbot-api.tls=true
      - traefik.http.routers.reqbot-api.tls.certresolver=default
      - traefik.http.services.reqbot-api.loadbalancer.server.port=5000
      - traefik.http.services.reqbot-api.loadbalancer.server.scheme=http

  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    networks:
      - reqbot
    volumes:
      - /srv/req/mongo:/data/db

  redis:
    networks:
      - reqbot
    image: redis:7
    container_name: redis
    restart: unless-stopped


